---
# Project Information
site_name: kci-dev
site_author: Arisu Tachibana
site_description: >-
    kci-dev is a cmdline tool for interact with a 
    enabled KernelCI server.

# Repository information
repo_name: kernelci/kci-dev
repo_url: https://github.com/kernelci/kci-dev
edit_uri: ""

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
  language: en

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kernelci
      name: kernelci on GitHub

# Page tree
nav:
  - Home:
    - Introduction: index.md
