baseURL = 'https://kci.dev/'
languageCode = 'en-us'
title = 'kci-dev'
description = 'Stand alone tool for Linux Kernel developers and maintainers to interact with KernelCI'
contentDir = "docs/"

[minify]
  disableXML = true
  minifyOutput = true

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowToc = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  useHLJS = true
  defaultTheme = "auto"

  [params.search]
    enable = true
    type = "lunr"
    contentLength = 4000
    placeholder = ""
    maxResultLength = 10
    snippetLength = 50
    highlightTag = "em"
    absoluteURL = false

[menu]
  [[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 10

  [[menu.main]]
    name = "checkout"
    pageRef = "checkout/"
    weight = 20
  
  [[menu.main]]
    name = "config"
    pageRef = "config/"
    weight = 20
  
  [[menu.main]]
    name = "config_file"
    pageRef = "config_file/"
    weight = 20

  [[menu.main]]
    name = "testretry"
    pageRef = "testretry/"
    weight = 20

  [[menu.main]]
    name = "results"
    url = "results/"
    weight = 20
  
  [[menu.main]]
    name = "maestro-results"
    url = "maestro-results/"
    weight = 20
